apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-loadtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-loadtest
  template:
    metadata:
      labels:
        app: api-loadtest
    spec:
      containers:
      - name: api-loadtest
        image: SEU_USUARIO_DOCKER/minha-api:latest
        ports:
        - containerPort: 8000
